# Generated by Django 5.2 on 2025-05-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='carousel_image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_images'),
        ),
    ]
