# Generated by Django 5.2 on 2025-05-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyGame',
        ),
    ]
